Loading checkpoint from "/data/xhj/model/v4_nofeedback/latest.model-54.model"

53
0.00012978543772856094
924771
********Starting metrics evaluation on test dataset**********
/home/xhj/src/eval_composite.py:360: RuntimeWarning: invalid value encountered in log
  log_ = np.log(numerator / denominator)
Numerator: [[0.00299791]]
Denominator: [[-2.3382046e-05]]
Numerator: [[0.00021813]]
Denominator: [[-3.4215645e-05]]
Numerator: [[0.00379762]]
Denominator: [[-0.00010177]]
Numerator: [[0.00147137]]
Denominator: [[-0.00017934]]
Numerator: [[0.00133635]]
Denominator: [[-0.00055303]]
Numerator: [[0.0057602]]
Denominator: [[-0.00165695]]
Numerator: [[0.00623186]]
Denominator: [[-4.259846e-05]]
Numerator: [[0.00029995]]
Denominator: [[-9.481683e-05]]
Numerator: [[0.00154143]]
Denominator: [[-0.0021542]]
Numerator: [[0.00274224]]
Denominator: [[-0.00036474]]
Numerator: [[0.00199197]]
Denominator: [[-0.00194905]]
Numerator: [[0.00472682]]
Denominator: [[-0.00060675]]
Numerator: [[0.00275435]]
Denominator: [[-0.00011474]]
Numerator: [[0.00333545]]
Denominator: [[-0.00223267]]
Numerator: [[0.00613956]]
Denominator: [[-0.00010729]]
Numerator: [[0.012429]]
Denominator: [[-0.00211089]]
STOI: 0.9470
SSNR: 9.4426
PESQ: 3.0078
CSIG: 4.3247
CBAK: 3.5396
COVL: 3.6882
